# config.yaml

project:
  name: "Simba"
  version: "1.0.0"
  api_version: "/api/v1"

paths:
  base_dir: null  # Will be set programmatically
  faiss_index_dir: "vector_stores/faiss_index"
  vector_store_dir: "vector_stores"

llm:
  provider: "vllm"
  model_name: "mlx-community/Llama-3.2-3B-Instruct-4bit"
  base_url: "http://localhost:8000"
  temperature: 0.0
  max_tokens: 4096
  streaming: true
  additional_params: {}

embedding:
  provider: "huggingface"
  model_name: "sentence-transformers/all-MiniLM-L6-v2"
  device: "mps"  # Keep mps for Mac performance
  additional_params: {}

vector_store:
  provider: "faiss"
  collection_name: "chunk_embeddings"

  additional_params: {}

chunking:
  chunk_size: 512
  chunk_overlap: 200

retrieval:
  method: "default" # Options: default, semantic, keyword, hybrid, ensemble, reranked
  k: 5
  # Method-specific parameters
  params:
    # Semantic retrieval parameters
    score_threshold: 0.5
    
    # Hybrid retrieval parameters
    prioritize_semantic: true
    
    # Ensemble retrieval parameters
    weights: [0.7, 0.3]  # Weights for semantic and keyword retrievers
    
    # Reranking parameters
    reranker_model: colbert
    reranker_threshold: 0.7

storage:
  provider: local



# Database configuration
database:
  provider: litedb # Options: litedb, sqlite
  additional_params: {}

celery: 
  broker_url: ${CELERY_BROKER_URL:-redis://redis:6379/0}
  result_backend: ${CELERY_RESULT_BACKEND:-redis://redis:6379/1}